CREATE TABLE IF NOT EXISTS units (
    id VARCHAR(36) PRIMARY KEY,
    propertyId VARCHAR(36) NOT NULL,
    unitNumber VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'Available',
    size DECIMAL(10, 2),
    sizeUnit VARCHAR(50),
    price DECIMAL(15, 2),
    description TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (propertyId) REFERENCES properties(id) ON DELETE CASCADE
);
