
CREATE TABLE IF NOT EXISTS lease_payments (
    id VARCHAR(255) PRIMARY KEY,
    leaseId VARCHAR(255) NOT NULL,
    dueDate DATE NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    chequeNumber VARCHAR(255),
    chequeImageUrl VARCHAR(2048),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (leaseId) REFERENCES leases(id) ON DELETE CASCADE
);
